ParkingApp/Controllers/ParkingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Domain.Entities;
using Domain.Interfaces.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ParkingApp.Models;

namespace ParkingApp.Controllers
{
    public class ParkingController : Controller
    {
        private readonly IParkingService _service;
        private readonly IMapper _mapper;
        private readonly ICountryService _countryService;

        public ParkingController(IParkingService service, IMapper mapper, ICountryService countryService)
        {
            _service = service;
            _mapper = mapper;
            _countryService = countryService;
        }

        public IActionResult Index()
        {
            var result = _mapper.Map<List<ParkingModel>>(_service.GetAll());
            return View(result);
        }

        public IActionResult Details(int id)
        {
            var result = _mapper.Map<ParkingModel>(_service.Get(id));
            return View(result);
        }

        [HttpGet]
        public IActionResult Edit(int id = 0, string message = null)
        {
            ParkingViewModel model = new ParkingViewModel();
            model.Countries = _mapper.Map<List<CountryModel>>(_countryService.GetAll());

            if(message != null)
            {
                ModelState.AddModelError("", "An error occurred while saving");
            }

            if (id > 0)
            {
                model.Parking = _mapper.Map<ParkingModel>(_service.Get(id));
                return View(model);
            }

            model.Parking = new ParkingModel();
            return View(model);
        }


        [Authorize]
        [HttpPost]
        public IActionResult Edit(ParkingViewModel model)
        {
            var parking = _mapper.Map<Parking>(model.Parking);

            try
            {
                if (parking.Id == 0)
                    _service.Save(parking, model.Parking.QuantitySpots, User.Identity.Name);
                else
                    _service.Put(parking);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return RedirectToAction("Edit", new { id = model.Parking.Id, message = "An error occurred while saving" });
            }

        }
    }
}

ParkingApp/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Domain;
using Domain.Interfaces.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ParkingApp.Models;

namespace ParkingApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private readonly IUserService _service;
        private readonly IMapper _mapper;

        public UserController(IUserService service, IMapper mapper)
        {
            _service = service;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var result = _mapper.Map<List<UserModel>>(_service.GetAll());
            return View(result);
        }

        public ActionResult Edit(int id)
        {
            var result = _mapper.Map<UserModel>(_service.Get(id));
            return View(result);
        }
        [HttpPost]
        public ActionResult Edit(UserModel model)
        {
            try
            {
                var user = _mapper.Map<User>(model);
                _service.Put(user);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "An error occurred while saving");
                return View();
            }
        }
    }
}

ParkingApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ParkingApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    @{
        var profile = User?.Claims?.Where(x => x.Type.Contains("role"))?.FirstOrDefault()?.Value ?? "";
        var isAdmin = (profile == "Admin") ? true : false;
     }
    
    <header>
        <nav class="navbar navbar-expand-md bg-dark navbar-dark sticky-top">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">ParkingApp</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navb" aria-expanded="true">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div id="navb" class="navbar-collapse collapse hide">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    @if (isAdmin)
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                    }
                    @if(User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Parking" asp-action="Index">Parking</a>
                        </li>
                    }
                </ul>

                <ul class="nav navbar-nav ml-auto">
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Signup">
                                <span class="fas fa-user"></span>
                                Sign Up
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Login">
                                <span class="fas fa-sign-in-alt"></span>
                                Login
                            </a>
                        </li>
                    }
                    else
                    {
                        <li><p class="navbar-text" id="loginName">@User.Identity.Name</p></li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Logout">
                                <span class="fas sign-out-alt"></span>
                                Logout
                            </a>
                        </li>
                    }
                </ul>
            </div>
        </nav>


    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ParkingApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>